# http://www.appveyor.com/docs/appveyor-yml

# configuration for dev
-
  image: Visual Studio 2017
  branches:
    only:
      - dev

  version: 1.2.0-dev{build}

  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true

  configuration: Release
  platform: Any CPU

  build_script:
  - ./build.cmd AppveyorDev

  cache:
  - tools -> build.*
  - src\packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages -> **\project.json'

  artifacts:
  - path: Build\gong-wpf-dragdrop.*.nupkg
  - path: Build\Showcase.WPF.DragDrop.*.zip

# configuration for master
-
  image: Visual Studio 2017
  branches:
    only:
      - master

  version: 1.2.0.0

  pull_requests:
    do_not_increment_build_number: true
  skip_tags: true

  configuration: Release
  platform: Any CPU

  build_script:
  - ./build.cmd Appveyor

  cache:
  - tools -> build.*
  - src\packages -> **\packages.config
  - '%USERPROFILE%\.nuget\packages -> **\project.json'

  artifacts:
  - path: Build\gong-wpf-dragdrop.*.nupkg
  - path: Build\Showcase.WPF.DragDrop.*.zip
